# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71835a2cb2eace70fcd8969712bd036d57de1603c17814cad066b78f2dd158087c885003d0038bc8551708decb0ee563db5d41a4dfe0acc115a2e4c1181d1337

test:
  secret_key_base: d1ff04ec39c40de4c543e4488f5dab52b9ee4a51df67f987b4ee8838d4be0f41ccaf06898f3831cfc19b777d5cd3b38edf083e37a27bedcd68bad6674c58c2a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
